version: "3.7"

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - nightwatch-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  web-api:
    build:
      context: ./web-api
    ports:
      - "8080:8080"
    volumes:
      - nightwatch-maven-repository:/root/.m2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      JDBC_URL: ${DB_URL}
      JDBC_USERNAME: ${DB_USER}
      JDBC_PASSWORD: ${DB_PASSWORD}



volumes:
  nightwatch-postgres-data:
  nightwatch-maven-repository: